"""empty message

Revision ID: 93551355b60e
Revises: 845932d9e2e1
Create Date: 2023-10-04 22:48:43.616032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93551355b60e'
down_revision = '845932d9e2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episodes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['episodes_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_locations')
    op.drop_table('favorite_episodes')
    op.drop_table('favorite_characters')
    # ### end Alembic commands ###
