"""empty message

Revision ID: f5e42b16ecbb
Revises: 982e9162dc36
Create Date: 2023-10-05 21:43:08.324102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e42b16ecbb'
down_revision = '982e9162dc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_episodes_episodes_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'episodes', ['episode_id'], ['id'])
        batch_op.drop_column('episodes_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episodes_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_episodes_episodes_id_fkey', 'episodes', ['episodes_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('episode_id')

    # ### end Alembic commands ###
